### ISSUE TITLE
How to extract melody and harmony for training from multiple sound tracks

### ISSUE THREAD

**Issue by wangdelp** [yoavz/music_rnn#1]
Hi,
I have some midi files (https://freemidi.org/artist-1870-beyond#) I want to train on, it has different tracks (piano, rock guitar, acoustic guitar...). Sounds like the input midi should only contain melody and harmony, how do I extract that information and feed the data for training? Thank you.

**Comment by tthtlc** [comment]
> Traceback (most recent call last):
>   File "rnn.py", line 16, in <module>
>     from model import Model, NottinghamModel
>   File "/home/tteikhua/neural_network/music_rnn/model.py", line 5, in <module>
>     from tensorflow.models.rnn import rnn_cell
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/rnn_cell.py", line 21, in <module>
>     raise ImportError("This module is deprecated.  Use tf.nn.rnn_cell instead.")
> ImportError: This module is deprecated.  Use tf.nn.rnn_cell instead.

Not sure how the above error can be overcome?

**Comment by wzds2015** [comment]
Hi wangdelp,

Have you solved this issue? I haven't tried, but I am going to do the same thing. My understanding is we just need to extend the input api to make a longer sequence. For sure there are more codes need modifying, e.g every place like data[:, :, :r]. Correct me if this is not enough.

**Comment by wangdelp** [comment]
Sorry I did not try any further after that issue

**Comment by yoavz** [comment]
I only wrote melody and harmony extraction code for the dataset I was experimenting on (Nottingham), unfortunately. It is possible to extend this model to more tracks (have n softmaxes for n tracks), but you'll have to write the code to encode and decode each of the time step representations based on the dataset.
