### ISSUE TITLE
deprecation error:   tensorflow/models/rnn/rnn_cell.py

### ISSUE THREAD

**Issue by tthtlc** [yoavz/music_rnn#3]
> Traceback (most recent call last):
>   File "rnn.py", line 16, in <module>
>     from model import Model, NottinghamModel
>   File "/home/tteikhua/neural_network/music_rnn/model.py", line 5, in <module>
>     from tensorflow.models.rnn import rnn_cell
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/rnn_cell.py", line 21, in <module>
>     raise ImportError("This module is deprecated.  Use tf.nn.rnn_cell instead.")
> ImportError: This module is deprecated.  Use tf.nn.rnn_cell instead.

Not sure how the above error can be overcome?

**Comment by hiorws** [comment]
you have to use tensorflow==0.8.0
to install that, just uninstall the tensorflow

``` bash
pip uninstall tensorflow
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.8.0-py2-none-any.whl
```

i assume `rnn_cell.py` will be successfully work.

i hope it will help.

**Comment by tthtlc** [comment]
python -c 'import tensorflow as tf; print(tf.**version**)'
give me: 0.9.0

and so I must downgrade the TF version?   Latest version is already 0.11.

**Comment by hiorws** [comment]
Yes you have to use 0.8.0 version of tensorflow.

**Comment by bzamecnik** [comment]
Importing TensorFlow installed this way gives me:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bza/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/bza/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 45, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/bza/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/bza/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /home/bza/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: invalid ELF header
```

**Comment by bzamecnik** [comment]
Wrong build of TensorFlow installed. For my system (Ubuntu 16.04 + GPU):

```
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
```

https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html

**Comment by yoavz** [comment]
Thank you @bzamecnik for performing much needed maintenance! Closing for now
